zookeeper.connection-string=${ZOOKEEPER_HOST:localhost}:${ZOOKEEPER_PORT:2181}
grpc.server.port=${SERVER_PORT:9090}
server.port=${HTTP_PORT:8080}
management.server.port=${MANAGEMENT_PORT:8081}
logging.level.com.example=INFO
